DbBundle\Entity\Chef:
    type: entity
    table: chef
    indexes:
        id_user:
            columns:
                - id_user
        id_kesm:
            columns:
                - id_kesm
        id_jiha:
            columns:
                - id_jiha
    uniqueConstraints:
        cin:
            columns:
                - cin
        inscrit:
            columns:
                - inscrit
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            fixed: false
        cin:
            type: string
            nullable: false
            length: 255
            fixed: false
        inscrit:
            type: string
            nullable: false
            length: 255
            fixed: false
        dateNaissance:
            type: date
            nullable: false
            column: date_naissance
        fawej:
            type: string
            nullable: true
            length: 255
            fixed: false
        tel:
            type: string
            nullable: true
            length: 255
            fixed: false
        etude:
            type: string
            nullable: true
            length: 255
            fixed: false
        travail:
            type: string
            nullable: true
            length: 255
            fixed: false
        actif:
            type: integer
            nullable: false
            unsigned: false
        sex:
            type: integer
            default: 1
            nullable: false
            unsigned: false
        lastDirasa:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: last_dirasa
    manyToOne:
        idUser:
            targetEntity: \UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
        idKesm:
            targetEntity: Kesm
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_kesm:
                    referencedColumnName: id
            orphanRemoval: false
        idJiha:
            targetEntity: Jiha
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_jiha:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
