DbBundle\Entity\MarkezTadrib:
    type: entity
    table: null
    repositoryClass: DbBundle\Repository\MarkezTadribRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
    manyToOne:
        idLink:
            targetEntity: Link
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_link:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
