DbBundle\Entity\TypeDawra:
    type: entity
    table: type_dawra
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        code:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
