<?php

namespace DbBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChefTadribRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefTadribRepository extends EntityRepository
{
}
