<?php

namespace DbBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefRepository extends EntityRepository
{
    /**
     * @return Chef[] Returns an array of Livre objects
     */
    public function findByTadrib()
    {
       
        
       return  $this->createQueryBuilder('c')
                    ->andWhere('c.actif = 1')
                    ->andWhere('c.lastDirasa LIKE :dirasaT')
                    ->orWhere('c.lastDirasa LIKE :dirasaM')
                    ->setParameter('dirasaT', '%قائد تدريب%')
                    ->setParameter('dirasaM', '%مساعد قائد تدريب%')
                    ->orderBy('c.id', 'ASC')
                    ->getQuery()
                    ->getResult();
    }
}
