<?php

namespace DbBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DawraTadribRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DawraTadribRepository extends EntityRepository
{
}
