<?php

namespace DbBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InscritLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscritLinkRepository extends EntityRepository
{
}
