<?php

namespace DbBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RaportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaportRepository extends EntityRepository
{
}
